using HistoryPediaV2.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace HistoryPediaV2.Data.Configuration;

public class PicturesConfiguration : IEntityTypeConfiguration<Picture>
{
    public void Configure(EntityTypeBuilder<Picture> builder)
    {
        builder.HasData(
            new Picture(1,
                "RomanEmpIco",
                "/Images/RomanEmpIco.png"),
            new Picture(2,
                          "RomanEmp1",
                "/Images/RomanEmp1.png",
                "Map of the Roman Empire"),
            new Picture(3,
                          "RomanEmp2",
                "/Images/RomanEmp2.jpg",
                "The first Roman emperor Octavian Augustus"),
            new Picture(4,
                          "ByzantIco",
                "/Images/ByzantIco.png"),
            new Picture(5,
                          "Byzant1",
                "/Images/Byzant1.jpg",
                "Map of the Byzantine Empire"),
            new Picture(6,
                          "Byzant2",
                "/Images/Byzant2.jpg",
                "Byzantine money"),
            new Picture(7,
                          "RepublicIco",
                "/Images/RepublicIco.png"),
            new Picture(8,
                          "Republic1",
                "/Images/Republic1.jpg",
                "Senate of the republic"),
            new Picture(9,
                          "Republic2",
                "/Images/Republic2.jpg",
                "Survived temple in Rome"),
            new Picture(10,
                          "CarthageIco",
                "/Images/CarthageIco.png"),
            new Picture(11,
                          "Carthage1",
                "/Images/Carthage1.jpg",
                "View on ancient carthage"),
            new Picture(12,
                          "Carthage2",
                "/Images/Carthage2.jpg",
                "Carthage's most popular leader Hannibal Barka"),
            new Picture(13,
                          "PunicIco",
                "/Images/PunicIco.jpg"),
            new Picture(14,
                          "Punic1",
                "/Images/Punic1.jpg",
                "Sea battle of the first punic war"),
            new Picture(15,
                          "Punic2",
                "/Images/Punic2.jpg",
                "Battle of the Cannaes"),
            new Picture(16,
                          "Punic3",
                "/Images/Punic3.jpg",
                "Assault of Carthage"),
            new Picture(17,
                          "ArmyIco",
                "/Images/ArmyIco.jpg"),
            new Picture(18,
                          "Army1",
                "/Images/Army1.jpg",
                "Early roman units"),
            new Picture(19,
                          "Army2",
                "/Images/Army2.jpg",
                "Caesar's legion"),
            new Picture(20,
                          "Army3",
                "/Images/Army3.jpg",
                "Legionaries of Roman Empire"),
            new Picture(21,
                          "Army4",
                "/Images/Army4.jpg",
                "Late roman soldiers"),
            new Picture(22,
                          "DefIco",
                "/Images/DefIco.png"),
            new Picture(23,
                          "Def1",
                "/Images/Def1.jpg",
                "What a picture!")
        );
    }
}